### ISSUE TITLE
Support for CustomID

### ISSUE THREAD

**Issue by broksonic21** [sanjay-io/strapi-provider-upload-cloudflare#3]
Cloudflare supports custom IDs (so the ID of the URL is meaningful instead of "upload_ba7d23f8ddb581bcb1a9999a99990ff9" like you get now). Strapi supports giving you a hash which can be used. 

Cloudinary plugin uses the hash already for this (see https://github.com/strapi/strapi/blob/main/packages/providers/upload-cloudinary/src/index.ts#L34 

For docs, see: https://developers.cloudflare.com/images/cloudflare-images/upload-images/custom-id/

code change looks to be as simple as:

Turning this:

https://github.com/sanjay-io/strapi-provider-upload-cloudflare/blob/main/lib/index.js#L12-L16

into

```
return axios.post(
    `https://api.cloudflare.com/client/v4/accounts/${config.accountId}/images/v1`,
    {
      file: file.stream || file.buffer,
      id: file.hash
    },
```

(i.e. add the id)

Any concerns? would you want this to be optional?

**Comment by sanjayiothakur** [comment]
My apologies for missing this. 

I don't see the harm in adding `id` for everyone. Can you throw up a PR and I can approve and create a new version?

**Comment by broksonic21** [comment]
No problem - PR: [https://github.com/sanjay-io/strapi-provider-upload-cloudflare/pull/4](https://github.com/sanjay-io/strapi-provider-upload-cloudflare/pull/4)

**Comment by broksonic21** [comment]
@sanjay-io thoughts? I'd love to use this soon. thanks!

**Comment by broksonic21** [comment]
@sanjay-io checking in on this one - thanks! Sorry for push!

**Comment by broksonic21** [comment]
@sanjay-io checking in on this one - thanks! Sorry for push!
